version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: shadowhawk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shadowhawk

  backend:
    build: ./server
    container_name: shadowhawk-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/shadowhawk
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: .
    container_name: shadowhawk-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: